apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  type: LoadBalancer
  selector:
    component: spring-boot-app
  ports:
    - port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  selector:
    matchLabels:
      component: spring-boot-app
  replicas: 2
  template:
    metadata:
      labels:
        component: spring-boot-app
    spec:
      containers:
        - name: users-api
          image: teja278/users-mysql:latest
          ports:
            - containerPort: 8086
          livenessProbe:
            httpGet:
              path: /all/
              port: 8086
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /all/
              port: 8086
            initialDelaySeconds: 10
            periodSeconds: 20